[project]
name = "back_sing"
version = "0.1.0"
description = ""
requires-python = ">=3.12"
dependencies = [
    "bentoml>=1.4.30",
    "fastapi>=0.124.4",
    "librosa>=0.11.0",
    "websockets>=15.0.1",
]
