[project]
name = "back_sing"
version = "0.1.0"
description = ""
requires-python = ">=3.12"
dependencies = [
    "bentoml>=1.4.30",
    "dotenv>=0.9.9",
    "fastapi>=0.124.4",
    "gradium>=0.5.4",
    "librosa>=0.11.0",
    "websockets>=15.0.1",
    "tensorflow==2.20.0",
    "crepe==0.0.16",
]
